// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultWorkers() {
  return window['go']['main']['App']['DefaultWorkers']();
}

export function RuntimeInfo() {
  return window['go']['main']['App']['RuntimeInfo']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartConversion(arg1) {
  return window['go']['main']['App']['StartConversion'](arg1);
}
