// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConverterStatus():Promise<main.ConverterStatus>;

export function DefaultWorkers():Promise<number>;

export function RuntimeInfo():Promise<Record<string, string>>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;


export function ValidateInput(arg1:string):Promise<string>;

export function StartConversion(arg1:main.ConvertRequest):Promise<main.ConvertResult>;
